### ISSUE TITLE
Get rid of jQuery dependency.

### ISSUE THREAD

**Issue by RangerMauve** [tparisi/glam#42]
Taking a look in the code, you're barely using much from jQuery at all. It might make sense to get rid of it as a dependency and use some smaller libraries for Ajax and whatever `$.parsecss` does.

**Comment by tparisi** [comment]
amen... let me think about it

**Comment by tparisi** [comment]
Fixed https://github.com/tparisi/glam/commit/17548b796ebfc09adc8be6a0ba20db8b23b59e2a
