### ISSUE TITLE
Tutorial / Offical Website

### ISSUE THREAD

**Issue by Miserlou** [tparisi/glam#43]
You need more documentation!

WebVR is a real thing now and if you actually want people to use this (I am a person who wants to use this), you actually need to make a page explaining how it's supposed to be used. GitHub provides free git-based static hosting that makes this very easy to do! Please consider taking an hour and making a nice guide (and instructions on how best to contribute).

Thanks!
R

**Comment by tparisi** [comment]
Have you been to glamjs.org?

Tony Parisi
CTO at Large
415.902.8002

**Comment by psema4** [comment]
Unfortunately, while [glamjs.org](http://glamjs.org/) has useful examples, it doesn't really provide much in the way of direct documentation.

An hour is unlikely to be enough for useful documentation though: the very first thing I did with glam was to create a rough list of it's classes and constructor signatures; that took a couple hours alone, doesn't cover any CSS or tags and is of rather poor quality (it's not really worth sharing; [jsdoc](http://usejsdoc.org/) tags in the sources would be far superior and allow for documentation to be generated automatically by #33)

That all said, I found @tparisi's [Sept 2014 slides](http://www.slideshare.net/auradeluxe/glam-35009205) helpful for getting started. It took me a bit realize the importance of [Vizi](https://github.com/tparisi/Vizi) (see also #29) - I would definitely recommend spending some time reviewing the code from both projects.

In addition to contributer instructions, I'd also like to suggest a Google Group or mailing list for general conversation; I'm hesitant to ask some questions as they're not really issues...

**Comment by tparisi** [comment]
Howdy @psema4 yes Vizi is the foundation of the GLAM runtime. This is so important that indeed, #29 is devoted to integrating the two. Vizi is going to become the "GLAM engine" i.e. you can programmatically do stuff that you wouldn't do declaratively... though actually I think I am going to try to steer all future development in two directions: 1) use the DOM to program all your behaviors and 2) use Web Components as the extension mechanism. When all of this has been figured out, there might not even be much of Vizi left over. It could be just GLAM, GLAM-based components and Three.js if you want to do custom rendering of your own components.

**Comment by Miserlou** [comment]
I had not been to GlamJS.org - because there is no link to it in this repo! I didn't know it existed!

You need to set the official URL of the GitHub project, and you should include links to related websites and documentation in the README.md file. Simple stuff!

**Comment by tparisi** [comment]
Will do

**Comment by tparisi** [comment]
Done. See #44 and #45.
